### ISSUE TITLE
panick: The initial window is not initialized

### ISSUE THREAD

**Issue by USMortality** [zeqianli/tgv#22]
i tried this tool, but it fails: 
```
minimap2 -ax sr -Y --sam-hit-only -t 6 MN908947.3.fa SRR10971381_1.fastq SRR10971381_2.fastq | samtools sort -@ 6 - >"temp.bam"
tgv temp.bam -r 1:100 --no-reference

thread 'main' panicked at /Users/ben/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tgv-0.0.2/src/app.rs:96:13:
The initial window is not initialized
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: tgv::app::App::draw
   3: ratatui::terminal::terminal::Terminal<B>::draw
   4: tokio::runtime::park::CachedParkThread::block_on
   5: tokio::runtime::context::runtime::enter_runtime
   6: tokio::runtime::runtime::Runtime::block_on
   7: tgv::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by zeqianli** [comment]
Hi, thanks for reporting. Can you share a subsampled version of the bam file for me to reproduce the bug?

**Comment by USMortality** [comment]
Yes, here's a subsample of 100 reads:

[subset.bam.zip](https://github.com/user-attachments/files/19670443/subset.bam.zip)

Or here's how you could do the full alignment, its from the origianl SARS-CoV-2 dataset: 
```
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR109/081/SRR10971381/SRR10971381_1.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR109/081/SRR10971381/SRR10971381_2.fastq.gz

echo "MN908947.3" | xargs -I {} sh -c 'curl "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&rettype=fasta&id={}" > {}.fa'

```

**Comment by zeqianli** [comment]
Thank you! Can I commit this data in and use for future testing?

**Comment by USMortality** [comment]
Yes, the source SRR is in the public domain.

**Comment by zeqianli** [comment]
Merged the fixes in #23 . Can you try again? 

`tgv temp.bam -r 1:100 --no-reference` is actually because the contig name `1` is not detected in the BAM header. `-r MN908947.3:100` would work. The error message was confusing and is fixed in this PR. 

In the future, maybe the CLI interface can be improved to not force the full contig name.

I also found a subtraction overflow problem and fixed it, too.

I added the bam file as part of the integration test! It seems to work well.

**Comment by zeqianli** [comment]
I reproduced the error. Turns out I wasn't calculating cigar coordinates correctly! 

Fixed in #28 . Try again?

On a side note, I noticed that there are >300K reads at the very end of the alignment, and the program became extremely slow. I initially thought something messed up the memory, but it was just loading all the data. Most of the reads seem low-quality, though. I think this will be a nice feature: 
- https://github.com/zeqianli/tgv/issues/29
- https://github.com/zeqianli/tgv/issues/30

**Comment by USMortality** [comment]
Did you update the homebrew version? I'm still getting the same error.

```sh
~/d/o/M/datasets (master) · brew tap zeqianli/tgv
==> Tapping zeqianli/tgv
Cloning into '/opt/homebrew/Library/Taps/zeqianli/homebrew-tgv'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 9 (delta 1), reused 9 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (9/9), done.
Resolving deltas: 100% (1/1), done.
Tapped 1 formula (13 files, 6.5KB).
brew instal⏎                                                                                         ~/d/o/M/datasets (master) · brew install tgv
==> Fetching zeqianli/tgv/tgv
==> Downloading https://github.com/zeqianli/tgv/releases/download/v0.0.3/tgv-aarch64-apple-darwin.tar
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/952
############################################################################################## 100.0%
==> Installing tgv from zeqianli/tgv
🍺  /opt/homebrew/Cellar/tgv/0.0.3: 4 files, 8.9MB, built in 1 second
==> Running `brew cleanup tgv`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
~/d/o/M/datasets (master) · tgv temp.bam -r MN908947.3:100 --no-reference

thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rust-htslib-0.49.0/src/bam/record.rs:1600:6:
index out of bounds: the len is 59 but the index is 59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
~/d/o/M/datasets (master) · tgv --version
tgv 0.0.3
```

**Comment by zeqianli** [comment]
Not yet, I'll deploy to brew in the next release. For now you can build from the main branch `cargo install --path .`

**Comment by USMortality** [comment]
Yes no more error. Thx!
